### ISSUE TITLE
zune-inflate fails to decompress some valid inputs

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#14]
I've added a fuzz target in https://github.com/etemesi254/zune-image/pull/13 that compresses arbitrary data from the fuzzer with `miniz_oxide`, then decompresses it with `zune-inflate`, and validates that the decompressed data is the same as the data before compression.

Right now this causes panics in `zune-inflate`, indicating that it cannot handle some valid inputs.

I've already tested `miniz_oxide` itself with this kind of fuzzing (decoding with miniz_oxide also), so I'm reasonably certain the compressed data it produces is correct.

**Comment by etemesi254** [comment]
Working on it.

Appreciate the efforts btw

**Comment by etemesi254** [comment]
Fixed most of the errors, thanks for the idea, never thought of it.

Round tripping works but now it reports false positives when using `ptr::copy`, and the fix reduces performance.

The problem is like this.

For all copies, the copier does what I call unconditional copy, i.e copy some fixed amount of bytes always  https://github.com/etemesi254/zune-image/blob/d46daae158b72c85d5d809e5786d33a2db808f6b/zune-inflate/src/decoder.rs#L417-L420.

This is beneficial as it allows the copier to keep high throughput for short copies, because we don't need to set up the slightly more expensive long copier loop. https://github.com/etemesi254/zune-image/blob/d46daae158b72c85d5d809e5786d33a2db808f6b/zune-inflate/src/decoder.rs#L453-L496

But when the copy is less than `FASTCOPY_BITS` away, (currently 16), the source and the dest will overlap.
Even though I'm using `ptr::copy`  which allows overlapping copies, AddressSanitizer doesn't like it.
Valgrind doesn't complain about it.

All other inputs work as of commit b290c056fb94a239f8c3eb4090c970c8355913ed

**Comment by Shnatsel** [comment]
Interesting. If this is a false positive, then it's the first one I've ever seen from Address Sanitizer.

Do I understand correctly that FASTCOPY_BITS is not actually in bits (that would be a u16) but in bytes (16 bytes, 128 bits)  which corresponds to a typical SIMD instruction length?

I am not thrilled about `const_copy` accepting a boolean flag for safety. This masks an unsafe operation because the function is not an `unsafe fn`. Could it be split into two functions, `fn const_copy` and `unsafe fn const_copy_unchecked`?

**Comment by etemesi254** [comment]
I guess I need to explain a bit about `const_copy`.

All fast implementations of decompressors, whether zlib, zstd, oodle, lz4 or whatever new fast decompressor fancy's ones pants  have two stages, a stage where inputs and outputs are far away from the end and a stage where inputs/outputs are near the end,explained in wuffs article.

In the fast loop you generally are assured that both the input and output buffer has X bytes available before proceeding and you can do what is called sloppy copying where you copy some select number of bytes, and then increment your destination depending on the length.

So as an optimization, if the length was anything less than your sloppy copy, the copying routine becomes , copy slop bytes, increment destination offset, which generally improves performance as you don't issue too many instructions to the MMU and you don't have to do many branches.

So `const_copy` is special in that the compiler can see that we are copying `FASTCOPY_BITS`(to be changed to `FASTCOPY_BYTES` ,yes your understanding was right ) which it can optimize to a simple SSE copy instead of calling `memmove`, `const_copy` is used in the first stage as we have the freedom to copy however we like.(we have confirmed the inputs and outputs are in bounds in the loop), 
the boolean flag there is used as a toggle,  and it was to help me confirm during development if I'm in bounds during certain operations and all current invocations set it to false. For the careful closer to end loop, we use 

I cannot check all operations to be in bounds as that defeats the purpose of a sloppy loop, but I will mark it unsafe in future revisions with reasons as to why it is that way.

**Comment by Shnatsel** [comment]
If you want to use those checks for development, I suggest dropping the boolean flag and using `debug_assert!()`. 

You can use a custom Cargo profile for development with debug assertions enabled, or simply prepend `RUSTFLAGS='-Cdebuginfo=2'` to your Cargo command, e.g. `RUSTFLAGS='-Cdebuginfo=2' cargo build --release`.

More info: https://doc.rust-lang.org/rustc/codegen-options/index.html#debug-assertions

This also has the added benefit of running these assertions in tests and when fuzzing, preventing future regressions.

**Comment by Shnatsel** [comment]
Ah, I know what the problem is. And it's not actually a false positive.

The problem is in the `split_at_mut` and the signature of `const_copy` that accepts two slices. It is undefined behavior in Rust to read or write out of bounds of a slice, even if it just so happens to be followed by other valid memory. (In fact this is UB in C as well, but it's even more problematic in Rust.)

So here's a minimized example of the problem in the Rust playground:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1c23a648fc6dea2a621f7bcc2386792a
Select "Tools > Miri" to see the issue.

The compiler (rightfully) takes advantage of the knowledge that UB never happens in valid programs, and so optimizes the `ptr::copy` into `ptr::copy_nonoverlapping`, which ASAN detects and complains about.

The fix would be to pass a single slice to `const_copy` instead of two different slices - see  [`slice.copy_within`](https://doc.rust-lang.org/stable/std/primitive.slice.html#method.copy_within) for a way to do this that does not trigger UB.

**Comment by etemesi254** [comment]
Ah my bad!  

`slice.copy_within` works, but it's a perf regression of about 1.5%, it introduces a bounds check somewhere where instruction flow  matters. 

So I replaced it with an unsafe version of `slice.copy_within`, no more perf regressions and no more complaining on AddressSanitizer's side.

Marking all the `const_copy` as unsafe and explaining why, sending the new commit in a few.

That was a pretty good catch btw.

**Comment by etemesi254** [comment]
See 77a25331d44a8e910f8ca9f778880ea82725e4e4 and 44ec96ee3c6061d09d2f068fd86c6d521c93dc9e, you could try testing on your side now, if any inputs fail feel free to report here, if none feel free to close

**Comment by Shnatsel** [comment]
I'll leave the fuzzer running overnight; if it finds anything, I'll open a new issue.

Thanks a lot for the fixes!

**Comment by Shnatsel** [comment]
No more issues on this fuzz target after 1 billion executions. I've used an ARM server with lots of cores to speedrun fuzzing. Here's the resulting corpus, in case you want to kickstart further fuzzing attempts: [corpus.tar.gz](https://github.com/etemesi254/zune-image/files/10297947/corpus.tar.gz)
