### ISSUE TITLE
JPEG decoding error: marker SOI found where not expected

### ISSUE THREAD

**Issue by djc** [etemesi254/zune-image#167]
We're seeing a lot of these errors (when downloading images from Instagram). Pretty sure this did not happen before the image 0.25 upgrade.

**Comment by djc** [comment]
I think this an example image that triggered this error in our code:

![marker-soi](https://github.com/etemesi254/zune-image/assets/158471/464cbc39-bc8b-4f74-b0cc-5cd908b81023)

**Comment by etemesi254** [comment]
Hi, this may sound really stupid, but your one image is actually two images, 

JPEG images end in an FF D9 marker, when we see that, we assume we have hit the end of image
But before the end of the image, there is usually some compressed data, so the decoder as an optimization, does what I call optimized reading, we always read 4 bytes, and if we meet a header, we discard the previous read.

So it happens that when your first image ends, your second image starts, so we meet the end of the image, see the FF D9 (we call it End of Image EOI marker) but because we read a bit more, we also see the Start of Image marker (SOI), 


To diagnose this, search for FF D9 in a hex image on the image attached, you'll find 2 occurences, where the first image stops, and the second image starts

Here's the attached secret image

![photo2](https://github.com/etemesi254/zune-image/assets/24320659/70985604-3d98-44b1-9a81-4a44e3f43853)

**Comment by etemesi254** [comment]
Now the decoder has two modes, a more strict compliance that doesn't allow such things through, and a less restrictive one that would have just logged an error, it seems image-rs chose the former as the default,  you can see the code that handles that at https://github.com/etemesi254/zune-image/blob/ba38f3fd50294ed68df5ee382898ea1af185555f/crates/zune-jpeg/src/mcu.rs#L279-L298

**Comment by djc** [comment]
It seems to me that image-rs chose the default as the default -- that is, it doesn't modify the zune-jpeg default options. Maybe zune-jpeg should be more permissive about this by default -- that is, should not default to strict mode at least for this? It seems to happen a decent amount at least in our downloads of Instagram images.
