### ISSUE TITLE
Roadmap to production

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#2]
To get zune-image's decoders into the hands of users, these things need to be done:

1. Fuzz the decoders (since unsafe SIMD is used which doesn't insert bounds checks)
2. Test the decoders on real-world images that technically aren't compliant but libjpeg-turbo decodes anyway
3. Write an adapter to the `image` crate so that its existing users could benefit without API changes

I think polishing and shipping JPEG first is a reasonable plan, but I'm curious what you think.

Also, please let me know once each decoder is ready for real-world testing and fuzzing - I can help with that!

**Comment by etemesi254** [comment]
Jpeg is done.

It's lean ,mean and green :)


It doesn't have any unsafe, apart from platform specific intrinsics.(same as zune-jpeg)

And it works with quite little memory usage.

That's ready for production.

But there are some incompatibilities with the decoder in that it works with memory buffers and not items that implement Read trait,

Using items that implement read trait is a performance detriment ( one of the many reasons jpeg decoding is slow in image-rs)


And then we get into a whole lot of differences, let me put that in the next comment

**Comment by etemesi254** [comment]
The one thing to understand is this library is fundamentally different from imagers internally. Here are the invert functions copy pasted


Invert in imagers
```rust
/// Invert each pixel within the supplied image.
/// This function operates in place.
pub fn invert<I: GenericImage>(image: &mut I) {
    // TODO find a way to use pixels?
    let (width, height) = image.dimensions();

    for y in 0..height {
        for x in 0..width {
            let mut p = image.get_pixel(x, y);
            p.invert();
            image.put_pixel(x, y, p);
        }
    }
}
```
Invert in zune-image
 ```rust
pub fn invert<T>(in_channel: &mut [T])
where
    T: NumOps<T> + Sub<Output = T> + Copy
{
    for pixel in in_channel.iter_mut()
    {
        *pixel = T::max_val() - *pixel;
    }
}
````
There are two reasons why  the first is slow one being that `image.get_pixel` probably has to do a bound check,  invert is a trait, careless use of the trait means the value will be accessed via a pointer call(inlining in Rust is quite finicky with traits, be careful),  and `image.put_pixel` might be doing a bounds check.

Mine does the same things, T::max_val gives me maximum value T can hold (only implemented for u8,u16 and u32, because compile time matters too), but it accepts a mutable reference to a single `image channel`, which represents a buffer of single channel data, i.e for typical images it is 3 buffers containing pure reds[RRR], pure blue[BBB] and pure green data[GGG], which means if we so wish we can parallelize it to run on three threads, but I don't.

Because it's fast enough on a single thread, the compiler will happily write beautiful SIMD for me to handle inverting u8 pixels, and do the same for u16, I don't have to do it myself,  the invert takes 91ms on your 14032x19844 AI upsacled image(from cmd run `zune --trace` for timings) or ` 9 Gb/s`  speed ( `(14032*19844)*3 * 1000 / 91`), memcpy runs at `11 Gb/s`.

Were image-rs to get such speed benefits, would mean a rewrite of probably everything, i.e rewrite what a pixel means+it's representation, how items are represented in memory, what is an image buffer, what is `GenericImage` and all, 
fundamentally incompatible things that do not constitute an abi change but a change in the whole system.

**Comment by Shnatsel** [comment]
I've just found #4 and #5, and there's probably more issues like these - if my past experience with image decoders is any indication. I wanted to know if you're interested in knowing about and fixing cases like those, or it's too early and you'd like to experiment with the design more before I run large-scale tests.

**Comment by Shnatsel** [comment]
> T::max_val gives me maximum value T can hold (only implemented for u8,u16 and u32, because compile time matters too)

There are already three ways to do that in the standard library, so you probably don't have to hand-roll it:

1. https://doc.rust-lang.org/stable/std/primitive.u64.html#method.max_value
1. https://doc.rust-lang.org/stable/std/u64/constant.MAX.html
1. https://doc.rust-lang.org/stable/std/primitive.u64.html#associatedconstant.MAX

**Comment by etemesi254** [comment]
> > T::max_val gives me maximum value T can hold (only implemented for u8,u16 and u32, because compile time matters too)
> 
> There are already three ways to do that in the standard library, so you probably don't have to hand-roll it:
> 
> 1. https://doc.rust-lang.org/stable/std/primitive.u64.html#method.max_value
> 2. https://doc.rust-lang.org/stable/std/u64/constant.MAX.html
> 3. https://doc.rust-lang.org/stable/std/primitive.u64.html#associatedconstant.MAX


They don't work in a generic way, i.e you can't know if an item has a generic max_val, the implementations call the max value internally, see https://github.com/etemesi254/zune-image/blob/main/zune-imageprocs/src/traits.rs

**Comment by etemesi254** [comment]
> I've just found #4 and #5, and there's probably more issues like these - if my past experience with image decoders is any indication. I wanted to know if you're interested in knowing about and fixing cases like those, or it's too early and you'd like to experiment with the design more before I run large-scale tests.

Any issue with decoding  is welcome, always appreciate your enthusiasm to image/videos/audio space in rust.

**Comment by Shnatsel** [comment]
> They don't work in a generic way, i.e you can't know if an item has a generic max_val,

Ahhh I see. That makes sense!

Thanks for explanation wrt `image`. I agree it's not feasible to make all the operations integrate with `image`. I was thinking of just having the format decoders output to a known format and cast the resulting buffer to some `image` type. I feel this is important because it would get `zune-jpeg` in the hands of users sooner - it wouldn't be blocked in finishing PNG or implementing GIF or any other format people may care about if they could just use `zune-jpeg` as a backend for the `image` crate.

**Comment by etemesi254** [comment]
> I've just found #4 and #5, and there's probably more issues like these - if my past experience with image decoders is any indication. I wanted to know if you're interested in knowing about and fixing cases like those, or it's too early and you'd like to experiment with the design more before I run large-scale tests.

There is `zune-tests` which I wanted to be the framework for testing the libraries, 
the initial gist of it was you run the decoder on certain outputs you know are correct and store the hash as a toml, 

with the following format 

```toml
[[file]]
file = "/tests/inputs/single_qt.jpeg"
hash = 10425199171900861388 # higher xxh128 hash bits
```

Since you are probably more versed with testing I wonder if you may have some guidelines/gotchas  or explanations of how that may look like or work.

The inspiration came from FFMPEG's FATE(see https://trac.ffmpeg.org/wiki/FATE/AddingATest for how it works)

**Comment by Shnatsel** [comment]
I don't think this will work for lossy formats like JPEG - hashes require the output to be bit-perfect, and there's no known-good way to decode JPEG. This might work for PNG but there's the issue of color transforms, etc.

What I use for testing is crude, but effective: I run `zune` conversion from JPEG to PPM, then run the difference operation in imagemagick between the original JPEG and the decoded PPM. Imagemagick decodes the JPEG internally and outputs the average difference between pixels. Then I sort the results by difference and look at high-difference results manually, and report bugs if there are visible discrepancies. I have ~60k JPEGs from disparate sources, so this should exercise the decoders rather well.

I suggest storing expected outputs in addition to the hashes - it doesn't have to be in the git repo, there's git LFS and other facilities that could be used for those. Then for lossy formats you could use fuzzy matching (not exceeding a max delta) while for lossless formats the matching could be exact. But there is no substitute for testing on a large corpus of real-world images.

**Comment by Shnatsel** [comment]
Now that JPEG works for all the files I have, I've reached out to a data hoarder to run it on their collection. They found no issues! :tada: 

I've also reached out to the admin of manebooru.art and asked them to run the same test on all of their images. They host 300,000 JPEGs. That showed a handful of divergences, with the highest one being 0.08, and only 25 decode failures across that entire dataset. I'll open an issue with the problematic files later, probably during the weekend.

**Comment by Shnatsel** [comment]
That is to say, zune-jpeg is really *really* close to being production-ready.

**Comment by etemesi254** [comment]
Some lovely news, hopefully preparing for a release soon.

**Comment by etemesi254** [comment]
I made the jpeg decoder work in a `no_std` environment, and was wondering if you know a way to add a test for CI to ensure this stays that way.

Compiling with `cargo c --no-default-features` fails since I don't provide `[alloc_error_handler]` and `[panic_handler]` so linking cannot happen(wondering why it needs to link though)

**Comment by Shnatsel** [comment]
Perhaps this will help? https://blog.dbrgn.ch/2019/12/24/testing-for-no-std-compatibility/

**Comment by Shnatsel** [comment]
And in particular https://github.com/hobofan/cargo-nono mentioned at the end of that post

**Comment by Shnatsel** [comment]
No more fuzzer issues on JPEG after 132 million executions. The only remaining issue with JPEG is [this one failing sample](https://github.com/etemesi254/zune-image/issues/12#issuecomment-1368274936).

**Comment by etemesi254** [comment]
Very good to hear.


Hope someone will one day report s more debugga le friendly image with the same characteristics as thag image.

**Comment by Shnatsel** [comment]
Alright, it's probably a good idea to cut a release and make an announcement regardless. That one problematic image is a one-in-350,000 case.

**Comment by etemesi254** [comment]
https://crates.io/crates/zune-jpeg

**Comment by etemesi254** [comment]
Done, hopefully should also be preparing for png release in 2-3 weeks.

**Comment by etemesi254** [comment]
LGTM 🎉

**Comment by etemesi254** [comment]
> How's this for an announcement? Any objections/comments/etc?
> 
> https://hackmd.io/@xmxSgN6MSImJPcY4MOKfjA/BJG1vKc0s

Title? Zune-jpeg not zune-inflate

**Comment by Shnatsel** [comment]
:facepalm: 

Fixed, thanks!

**Comment by Shnatsel** [comment]
Announcement published: https://www.reddit.com/r/rust/comments/11f4jre/announcing_zunejpeg_rusts_fastest_jpeg_decoder/
