### ISSUE TITLE
DecodingResult::u16_to_u8 is unsound

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#36]
https://github.com/etemesi254/zune-image/blob/306ad417254c7b99221e2aa3d007cfbbd145b1f4/zune-core/src/lib.rs#L72-L84

This code transforms a `Vec<u16>` into `Vec<u8>`. This cannot be done safely in Rust, or even in C, because memory must be allocated and deallocated with the same alignment, while the alignment requirements of `u16` and `u8` are different. 

[The documentation on `Vec::from_raw_parts`](https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.from_raw_parts) explicitly calls this out.

**Comment by Shnatsel** [comment]
You can, however, cast _slices_ instead of _vectors_, or basically any borrows instead of owned data.

I strongly suggest using the [`bytemuck`](https://docs.rs/bytemuck/1.12.3/bytemuck/) crate for this kind of conversions. 
It provides safe primitives for this kind of casting, is widely used, and the implementation is really simple which makes it trivial to audit.

**Comment by etemesi254** [comment]
My bad, I guess I never really read the docs.

This I do have an issue with though, and I was wondering if there was a way to do this without causing some weird errors.

Is there any way to have a vector move from u8->u16 ?

E.g for 16 bit pngs, I have to write things like


https://github.com/etemesi254/zune-image/blob/306ad417254c7b99221e2aa3d007cfbbd145b1f4/zune-png/src/decoder.rs#L340-L351

To convert the image finally to 16 bit png.

That allocation bothers me above there, because it may look harmless but for let's say a 4K image(3840*2160*4 channels) that becomes a 32 MB initialization with us having another 32 Mb that we discard shortly after.

**Comment by etemesi254** [comment]
It's removed now.

**Comment by etemesi254** [comment]
But the motivation for it was e.g if a user decoded 16 bit png and wanted an owned u8 as native endian, how would one go around that?

**Comment by Shnatsel** [comment]
This is once per image, right? In that case reusing allocations as I did in https://github.com/johannesvollmer/exrs/pull/176 makes little sense.

In general you cannot cast any owned types, because the memory must be allocated and deallocated with the same alignment - that's just `malloc()` restrictions. Various hacks are possible (e.g. custom `Drop` on a non-resizable boxed slice, wrapper around `[u8;2]` with the alignment of `u16`, roll your own allocator or Vec that always aligns, etc) but all make the API non-interoperable to use by introducing custom types.

So AFAIK there are two not-terrible options:

1. Store as `Vec<u16>` and cast to `&mut [u8]` as needed
2. Store as `Vec<u8>` and cast a slice to `&mut [u16]` as needed

Option 1 means that you have to perform that memory copy (although I know how to make it less terrible, PR coming soon). And also potentially lose interoperability with APIs that only accept `Vec<u8>` and not `&mut u8`, if they exist, although I can't name any off the top of my head.

Option 2 avoids the memory copy up front, but `u8` has a lower alignment than `u16`, so you cannot just trivially view it as u16 in memory. You have to either use iterators to access it (which desugar into `read_unaligned` internally) or check the alignment at runtime and only perform the memory copy if it didn't match (although I'm not sure the lifetimes will work out in this case, depending on the API; this might entail API weirdness still). This defers the memory copy, but may mean there are more of them total. `malloc()` isn't _guaranteed_ to return memory with any specific alignment, but in practice does align memory to a very high value on desktop platforms, so the copies can be assumed to be rare, provided this holds for the Rust APIs too.

**Comment by Shnatsel** [comment]
Won't you split the `[R, G, B, R, G, B]` samples into `[R, R], [G, G,], [B, B]` representation in `zune-image` anyway? In that case you might as well output a `Vec<u8>` always and perform the conversion along with deinterleaving, when you have to `memcpy()` anyway?

**Comment by Shnatsel** [comment]
I've edited the long message above with more info on Option 2. If you're reading this through email notifications, please check the updated message on github.

**Comment by etemesi254** [comment]
There needs to be a consistent api, we cannot have jpeg returning owned byyes and png retuning a view, I'd rather have another allocation.

I'd rather not have that property of png hidden to the end user, explicit is better than implicit


I will offer ways of converting u16 to u8 in DecodingResult with an allocation as that seems the only way forward and tell the user this will allocate a new vector.

I thought about using a custom allocation but realized that would be disruptive to everyone else binding to other allocations


That's why there is a special Channel class in zune-image that aligns allocations to a high number and adds various assertions to ensure that data can be viewed as whatever type.

See channels , reinterpret_as and reinteptete_as_mut methods

**Comment by etemesi254** [comment]
Rust doesn't have template specialization, those de-interleaving are implemented in simd and need concrete types.(remember it's carried out for all images that enter, it cannot be slow) .

Simd is fixed width, meaning implementation for u8 is different from u16

This is also why zune-image doesn't support f32s or use generic code in zune-image,even if zune-imageprocs uses generics extensively, generics get concrete types at compile time for optimal code generation, e.g in zune-image/impls/brighten.rs we  instantiate two code paths, for u8 and u16 and then we choose what path we want during execution depending on image type.

**Comment by Shnatsel** [comment]
> There needs to be a consistent api, we cannot have jpeg returning owned byyes and png retuning a view, I'd rather have another allocation.

Well, PNG could always return a `Vec<u8>` and leave it up to the caller to convert it into any kind of view over `u16` if they so desire. This avoids an allocation up front and lets the user perform it if they need it.

And in `zune-image` you can still deinterleave `[u8; 2]` into `u16` in a loop with `chunks_exact_mut` and that will be automatically vectorized. You just need `zune-png` to convert the endianness in-place beforehand.

**Comment by etemesi254** [comment]
Well then what would happen if someone writes a simple png to webp converter and gets a 16 bit image represented as u8? 

Webp supports rgba up to 8 bits and there not a lot of 16 bit images, but when they meet such that becomes an issue in the future I'm trying to avoid.

**Comment by Shnatsel** [comment]
What if they get a 4-bit or 1-bit image? That also needs special handling. They'll just need to run a sample conversion function to do it correctly. Which zune-image should probably provide.

Besides, conditionally returning `u8` or `u16` also has its drawbacks. It's now a lot more difficult to treat the decoded PNG as opaque data and pass it around; now you have to explicitly deal with the `u16` case everywhere.

**Comment by etemesi254** [comment]
1,2 and 4 bit are upscaled to 8 bit, this makes sense still because when i do a[i*width + j] i get the pixel at that location, but 16 bit images what would a[i*width+ j] be?

And  I'd really rather they deal with it, I'm open to set decoder options or have one method that explicitly says we are returning u8 and 16 bit images will have the length twice as big as an 8 bit image with native endian encoding than hiding it and letting the user find out when someone decodes that esoteric image sent is horribly corrupt.

**Comment by etemesi254** [comment]
Also take wasm for example, the canvas only works with 8 bit per pixel images. I can bet that naively displaying 16 bit images in wasm will create garbled up images unless the author has explicit support.

And I for one didn't know about higher bit images until I started playing with image decoders

**Comment by Shnatsel** [comment]
FWIW the `png` crate used to  upsample everything to at least 8 bit as well, and eventually changed it because people asked: https://github.com/image-rs/image-png/pull/270

But I agree that the scenario you describe is a problem.

How about providing different methods, one for `raw_samples` and one for samples converted to `u8` even if they were `u16` originally? This allows the "easy" use of everything-as-u8, as well as advanced use of raw data if need be.

**Comment by etemesi254** [comment]
> How about providing different methods, one for raw_samples and one for samples converted to u8 even if they were u16 originally? This allows the "easy" use of everything-as-u8, as well as advanced use of raw data if need be.

Yes this makes sense,

**Comment by Shnatsel** [comment]
This has been fixed, closing.
