### ISSUE TITLE
PNG: test decoding on lots of real-world images

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#51]
I have a large corpus of PNGs lying around, and I should run decode comparison tests against libpng. Just let me know once the decoder is complete enough for that kind of testing.

**Comment by etemesi254** [comment]
Yes

There are P1-P7 formats for ppm

Format p5 is grayscale/luma
Format p6 is rgb

Format p7 adds support for rgb,rgba and luma, lumaA

The ppm encoder chooses what format to use based on the colorspace of zune-image

I.e if its grayscale it's encoded in p5, images with alpha get to use p7, this isn't widely supported, e.g KDEs image viewer won't show it(it may say corrupt image), imagemagick convert supports it and ffmpeg can also be used

**Comment by etemesi254** [comment]
> I have indeed seen some issues with gamma. I wasn't sure if it would be useful to post them at this stage.
> 

The gamma issue is a weird one, and as usual arises from incompatibilities between decoders

-spng decodes and does gamma handling
- libpng doesn't seem to do it?? (Not yet confirmed)
- stb_image doesn't do it
-image-rs/png returns the gamma value, i don't think it does the gamma handling itself
- ffmpeg doesn't do it(or might do it in a different stage)

- imagemagick I'm not so sure

The problem usually comes during processing, i.e when doing color processing/blending images must be in linear form, otherwise too dark and too bright images won't be correctly rendered, so anything that ever does pix=input_pix(+-)value whre input pix is the color pixel and value is the output value needs linear colorspace 

This means things as simple as brightening may be wrongly implemented for this crate and a lot out there( we simply define brightness as an increase in 
pixel values)

And also about conversion

Take for example png to jpg conversion

You want the output to resemble the input
Depending on your viewer and your converter and how both  handle gama chunk for png, you may end up with a  different looking image than what you see


A good reference is https://matt77hias.github.io/blog/2018/07/01/linear-gamma-and-sRGB-color-spaces.html

That does a good explanation on colorspaces
An important place is color operations

**Comment by etemesi254** [comment]
We should now have a fully compliant decoder, if there are any test images causing errors, feel free to report them.

**Comment by Shnatsel** [comment]
The PNG decoder now shows no decode failures and no divergences from `convert`, other than https://github.com/etemesi254/zune-image/issues/70#issuecomment-1411091010 (the issue may have been closed prematurely, I'm not sure).

A test run on the entire dataset of manebooru.art is in progress, but so far the indications are positive - `convert` chokes on those PNGs far more frequently than `zune` does.

PNG is so close to being production-ready!

**Comment by etemesi254** [comment]
Could you run one last test on your png corpus, specifically your own corpus.

I've finished the changes I was working on(using less/small allocations) and the small tests pass locally, but I'd be more comfortable if they work on a varied corpus, as they are a bit complicated.

Somewhere this week, I'll add a pass for https://github.com/etemesi254/zune-image/issues/76 to ensure fuzzing works for those entries too and we can finally release

**Comment by Shnatsel** [comment]
Done, and it's all green now. `zune-png` can ship whenever you're ready.
