### ISSUE TITLE
ARM NEON support

### ISSUE THREAD

**Issue by inflation** [etemesi254/zune-image#93]
It would be nice to have NEON support. I could take a look at it, but feel free if anyone else is interested.

**Comment by etemesi254** [comment]
That's very good to hear. 

There are some hoops needed to be crossed though for compatibility with the whole crate ( it's quite big)


1. Add detection support in zune-core. In ways that allow the following to work

  - Compile time detection if the code is compiled with no_std but with features

- runtime detection if the code is compiled with std and the feature doesn't exist

- ability to dynamically disable neon paths(mainly for testing) .


This is already implemented for used x86 intrinsics in decoders in zune-core/options/decoder_options.rs

If this is confusing I could take a stab at it before you start changes

**Comment by etemesi254** [comment]
Then the work in jpeg is quite straightforward.

I'll walk you through idct which is the one part probably needing a neon implementation

Defune a function  with the same params and as idct_scalar in zune-jpeg/idct/scalar.rs

The file should be inside idct directory with the name of the extension, so probably neon.rs

The three parameters have the following functions

1. Array of  [i32; 64] dequantized coefficients which haven't been done idct, it's &mut so that you can reuse the space during transpose stage (scalar impl does it that way)


2. Out slice 

3. Width stride

Out slice is where you will write the output values clamped in 0-255, and you will write them in values of 8 i16's skipping width stride bytes after writing one stride 

The first position you write is `out_slice[0..8]`, next is out_stride[1*width_stride..]`, `out_stride[2*width_stride]` and so on and so forth.

**Comment by etemesi254** [comment]
For testing, you can use the zune binary to load jpeg images , if setup correctly `--safe` should disable neon intrinsics and you can use visual detection to see changes

(`cargo build -- release` should compile for you a working `zune` binary with complete jpeg support, hit `-h` for options)

**Comment by vgatherps** [comment]
I have a neon IDCT [here](https://github.com/vgatherps/zune-image/tree/neon_idct), it passes tests locally. Appears to be a ~30% performance improvement on my M1! However, I don't have a large corpus of JPEGs to test on - is there one that's relatively easy to download and test against?

For merging, It looks like there needs to be a two-step process. First, release a zune-core with options support for neon, and then merge the neon changes to zune-jpeg? Is there a reason that zune-jpeg depends on a cargo version of zune-core instead of the package in the repo?

**Comment by etemesi254** [comment]
@vgatherps  nice (also love the name)

Sadly I don't know of any large online corpus but perhaps @Shnatsel  may be of help.

Yea, you are right, we do need to do a double release.

Also curious how we stack up against other contenders in M1, 

Would you be willing to run `cargo benchmark --workspace` and post the results.

And thank you the changes look okay to me, feel fre to open a pr when satisfied

**Comment by Shnatsel** [comment]
@vgatherps getting good test corpora is rather tricky.

The most convenient thing would be a torrent with a large number of images from disparate sources, but in my experience such compilations only exist for porn. Machine learning datasets are all resized and encoded with a single set of parameters by a single tool, so they're quite useless for testing decoders.

The best I can offer off the top of my head is the [wallhaven dataset on archive.org](https://archive.org/details/WallhavenSexyWomen). You'll probably want a subset of that unless you're OK with downloading 260GB. It's not great wrt variety of encoding parameters, but it's the best easily accessible option that I'm aware of.

A booru-style imageboard makes for a perfect test corpus, but you'll need to either scour the internet for a dump or scrape them yourself. Many imageboards provide APIs or even database dumps, but you'll still have to write a script to download the images. You'll also have to do a bit of filtering yourself if you don't want to download the porn - fortunately the images are tagged with age ratings.

**Comment by Shnatsel** [comment]
The corpus I've been testing on locally is "all images from my data backups going back 10 years", but that likely contains sensitive information (scans of documents, etc), so unfortunately I cannot share that corpus.

**Comment by Shnatsel** [comment]
Ah, there is an easily accessible dump of danbooru: https://gwern.net/danbooru2021

That should cover lots of edge cases with different encoding parameters, etc. You'll still have to build a simple filtering script instead of just running `rsync` if you want to exclude the porn.

**Comment by Shnatsel** [comment]
[The differential fuzzing](https://github.com/etemesi254/zune-image/commit/ab770047915cd38eb40dff2fd9aa1c681f17b37c) for the vector IDCT implementations is a very good idea! This should help with testing a great deal.

I'll run the regular fuzz target on ARM with NEON enabled to check for potential memory safety issues. I don't expect to find any, but better safe than sorry.

**Comment by etemesi254** [comment]
> Is there a reason that zune-jpeg depends on a cargo version of zune-core instead of the package in the repo?

Yea sorry that was a mistake, it was to handle a release for zune-jpeg.  Cargo doesn't allow paths

Forgot to revert it

**Comment by Shnatsel** [comment]
You can specify both a path and a version. In this case when the path is found it will be used, otherwise it will fall back to downloading from crates.io. So you can have the same version specification both locally for development and published to crates.io.

**Comment by vgatherps** [comment]
> I'll run the regular fuzz target on ARM with NEON enabled to check for potential memory safety issues. I don't expect to find any, but better safe than sorry.

let me enable neon for the regular fuzz test - I got blowups in the scalar code due to multiplication overflow, but that's because you need to enable the correct neon features

**Comment by vgatherps** [comment]
> Ah, there is an easily accessible dump of danbooru: https://gwern.net/danbooru2021

Thanks, I'll find some time to download and give it a try.

**Comment by Shnatsel** [comment]
> let me enable neon for the regular fuzz test 

Cool, let me know once it's done and I'll run the fuzzer on ARM for a while.

BTW seen a dramatic difference in performance when fuzzing on ARM between a generic build and a `-C target-cpu=native` one. Is that because the runtime CPU feature detection via `is_aarch64_feature_detected!` is not wired up on ARM yet? If that's already wired up, then we should probably multiversion more functions.

**Comment by Shnatsel** [comment]
I've run the decode fuzzer on ARM on commit 851443c1f7660fdecd9638cf2cbc5a254b79bb78 with `-Ctarget-cpu=native` and found no issues after 850 million executions.

**Comment by Shnatsel** [comment]
You can also use the CommonCrawl data to get URLs of images published on the internet and then fetch them with your HTTP client of choice. This required surprisingly little parsing to get the URLs, I'm easily extracting WebP image URLs with a shell one-liner from WAT files.

**Comment by Shnatsel** [comment]
In case you need another corpus, here's [23,000 random JPEGs scraped off the web](https://mega.nz/file/05snVB7L#KK8rECA5oHGN-dWwdcvDztoqIysEfKxkLmNWlYApHQ8), discovered via CommonCrawl. The archive is just under 5GB.

This has not been filtered in any way, so if you run memory-unsafe programs on it like `imagemagick` I suggest doing so in a sandbox.

**Comment by Shnatsel** [comment]
I've run the test on the web JPEG corpus and found no divergences between running `zune --safe` and `zune` on ARM with `-Ctarget-cpu=native` on the NEON IDCT branch. So it seems the NEON support is correct and good to go!

@vgatherps would you open a pull request?

**Comment by etemesi254** [comment]
Hi @vgatherps pinging you on this issue, if you are busy, I could take some time to merge yoyr branch with dev.

Want to close this issue

**Comment by etemesi254** [comment]
Added and fixed in df6b9dc6f6b98fb28d3f5bc1ed827d5a554d3397, thanks
